server:
  port: 8080
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    driver-class-name: org.postgresql.Driver
    username: news_app
    password: news_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true
cache:
  type: LFU
  size: 20
client:
  users:
    url: localhost:8081/api/v1